version: 2
dist: build
before:
  hooks:
    - go mod tidy
    - go test -v ./...
builds:
  - id: k8tz
    binary: k8tz
    env:
      - CGO_ENABLED=0
    flags:
      - -v
    ldflags:
      - -s
      - -w
      - -X github.com/k8tz/k8tz/pkg/version.GitCommit={{ .FullCommit }}
      - -X github.com/k8tz/k8tz/pkg/version.AppVersion={{ .RawVersion }}
      - -X github.com/k8tz/k8tz/pkg/version.VersionSuffix={{ if .Prerelease }}-{{ .Prerelease }}{{ else }}{{ if .IsSnapshot }}-{{ .Branch }}{{ end }}{{ end }}
      - -X github.com/k8tz/k8tz/pkg/version.ImageRepository={{ if index .Env "IMAGE_REPOSITORY"  }}{{ .Env.IMAGE_REPOSITORY }}{{ else }}quay.io/k8tz/k8tz{{ end }}
    goos:
      - linux
      - windows
      - darwin
      - openbsd
      - netbsd
      - solaris
    goarch:
      - amd64
      - arm
      - arm64
      - s390x
      - 386
      - ppc64le
      - riscv64
    goarm:
      - 6
      - 7
archives:
  - id: k8tz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- if eq .Arch "386" }}i386
      {{- else }}
      {{- .Arch }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
      {{- end }}
checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-snapshot"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  github:
    owner: k8tz
    name: k8tz
  draft: true
  prerelease: auto
  header: |
    # Release k8tz {{ .Version }}

    We are happy to announce a new version of k8tz, these are the changes in this version:

  footer: |
    ## Docker images

    - `quay.io/k8tz/k8tz:{{ .Version }}`
    - `quay.io/k8tz/k8tz:{{ .Major }}.{{ .Minor }}`
    - `quay.io/k8tz/k8tz:latest`

    ## Install with Go

    ```console
    go install github.com/k8tz/k8tz@{{ .Tag }}
    ```

dockers_v2:
  - id: k8tz
    ids:
      - k8tz
    images:
      - quay.io/k8tz/k8tz
    tags:
      - "{{ .Version }}"
      - "{{ .Major }}.{{ .Minor }}"
      - latest
    platforms:
      - linux/amd64
      - linux/arm64
      - linux/386
      - linux/ppc64le
      - linux/arm/v6
      - linux/arm/v7
    labels:
      org.opencontainers.image.created: "{{ .Date }}"
      org.opencontainers.image.title: "{{ .ProjectName }}"
      org.opencontainers.image.revision: "{{ .FullCommit }}"
      org.opencontainers.image.version: "{{ .Version }}"
    flags:
      - --pull=true
    extra_files:
      - tzdata
