apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8tz.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "k8tz.labels" . | nindent 4 }}
spec:  
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "k8tz.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/admission-webhook.yaml") . | sha256sum }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "k8tz.selectorLabels" . | nindent 8 }}
    spec:
      volumes:
      - name: tls
        secret:
          secretName: {{ include "k8tz.fullname" . }}-tls
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "k8tz.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          args:
          - "webhook"
          - "--timezone"
          - {{ .Values.timezone | quote }}
          - "--injection-strategy"
          - {{ .Values.injectionStrategy | quote }}
          - "--inject={{ .Values.injectAll }}"
          - "--bootstrap-image"
          - "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          {{- if .Values.verbose }}
          - "--verbose"
          {{- end }}
          {{- if .Values.cronJobTimeZone }}
          {{- if and (ge .Capabilities.KubeVersion.Major "1") (ge .Capabilities.KubeVersion.Minor "24") }}
          - "--cronJobTimeZone"
          {{- else }}
          {{- fail "CronJob injection requires kubernetes >=1.24.0-beta.0 with 'CronJobTimeZone' feature gate enabled" }}
          {{- end }}
          {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - name: tls
              mountPath: /run/secrets/tls
              readOnly: true
          ports:
            - name: https
              containerPort: 8443
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          readinessProbe:
            httpGet:
              path: /health
              port: https
              scheme: HTTPS
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
