{{- if (and .Values.namespace .Values.createNamespace) }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.namespace }}
  labels:
    k8tz.io/controller-namespace: "true"
    {{- include "k8tz.labels" . | nindent 4 }}
    {{- with .Values.namespaceLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
